package com.bs.android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bs.android.model.SearchHistoryModel;

import com.bs.android.greendao.SearchHistoryModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryModelDaoConfig;

    private final SearchHistoryModelDao searchHistoryModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryModelDaoConfig = daoConfigMap.get(SearchHistoryModelDao.class).clone();
        searchHistoryModelDaoConfig.initIdentityScope(type);

        searchHistoryModelDao = new SearchHistoryModelDao(searchHistoryModelDaoConfig, this);

        registerDao(SearchHistoryModel.class, searchHistoryModelDao);
    }
    
    public void clear() {
        searchHistoryModelDaoConfig.clearIdentityScope();
    }

    public SearchHistoryModelDao getSearchHistoryModelDao() {
        return searchHistoryModelDao;
    }

}
